// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ylaolcqpevscbsoilavr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlsYW9sY3FwZXZzY2Jzb2lsYXZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAzNDQzMTUsImV4cCI6MjA3NTkyMDMxNX0.qG9WqjsLwAeN8tzOh6Kvg9q6vaPckhkbqu8yyW8TFkA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);